### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'defaultProject')

### ISSUE THREAD

**Issue by ryanbas21** [bikecoders/ngx-deploy-npm#471] opened 2023-01-29 02:17 UTC
its weird, seems when I debug locally the nxJson argument is undefined. 

However my version (latest nx) is not officially supported right now by this plugin. 15.6.3. 

So i'm going to guess 15.6.3 is the cause of this problem as its not officially supported and i've seen some issues along the lines of getting this plugin in line with the newer nx releases.
I created this issue because i had not seen this error itself anywhere.

For what its worth, nx.json does have a defaultProject key in this case. its just an undefined argument in this method of the Workspaces class here which is in Nx itself not this plugin but maybe it helps:
```
     calculateDefaultProjectName(cwd, projects, nxJson) {
        const relativeCwd = this.relativeCwd(cwd);
        if (relativeCwd) {
            const matchingProject = Object.keys(projects.projects).find((p) => {
                const projectRoot = projects.projects[p].root;
                return (relativeCwd == projectRoot ||
                    relativeCwd.startsWith(`${projectRoot}/`));
            });
            if (matchingProject)
                return matchingProject;
        }
        console.log('json?', nxJson)
        return nxJson.defaultProject;
    }
    ```

**Comment by dianjuar** [comment] 2023-01-30 19:47
So you have a project on 15.6.3 and it's failing, right?

**Comment by ryanbas21** [comment] 2023-01-30 20:33
> Let me try to understand. You have a project on 15.6.3, and it's failing, right?

This is correct

**Comment by dianjuar** [comment] 2023-02-01 14:49
@ryanbas21 I understand. Currently, on #470 we are working to have a solution.

**Comment by dianjuar** [comment] 2023-02-04 01:38
@ryanbas21 The potential fix is deployed under [ngx-deploy-npm@5.0.0](https://www.npmjs.com/package/ngx-deploy-npm/v/5.0.0).

Let us know if V5 solves your problem.

**Comment by dianjuar** [comment] 2023-02-04 02:04
I need help understanding the problem that you are facing. 

Recently we published (v5) to support more comprehensive versions of nx. I initially thought that was your problem, but I wonder if it is.

Can you provide this information to understand your case better:

```markdown
### Current Behavior
<!-- What is the behavior that currently you experience? -->

### Expected Behavior
<!-- What is the behavior that you expect to happen? -->

### GitHub Repo
<!-- This is extremely important! If this issue is reproduce-able on https://github.com/nrwl/nx-examples, you may use that as the repo.
If not, please do take a few minutes of your time to create a repo to help us reproduce the issue.
This is the best way to help us reproduce the issue and fix it as soon as possible. -->

### Steps to Reproduce
<!-- Please provide some instructions to reproduce the issue in the repo provided above. Be as detailed as possible. -->

1.

### Nx Report
<!-- Please paste the contents shown by nx report. This will be automatically formatted into code, so no need for backticks. -->

### Failure Logs
<!--  Please include any relevant log snippets or files here  -->

### Additional Information
<!-- Is there any additional information that you can provide? -->
```

**Comment by mogulx-operates** [comment] 2023-02-28 13:50
I'm running into this issue as well.  I have tried debugging for a bit but looking into other options.

**Comment by dianjuar** [comment] 2023-02-28 14:42
@mogulx-operates, can you please fill in the above list to try to reproduce your error?

**Comment by mogulx-operates** [comment] 2023-02-28 17:05
> @mogulx-operates, can you please fill in the above list to try to reproduce your error?

Meh, moving on.  Try to publish a package with the latest version of nx and you'll reproduce the error.

- Node: v16.18.0
- `npx create-nx-workspace@15.7.2 preset-ts --preset=ts`
- `npx nx@15.7.2 generate @nrwl/js:library vite-swc --unitTestRunner=vitest --bundler=vite --compiler=swc --directory=web --publishable --importPath=vite-swc`
- `npm install --save-dev ngx-deploy-npm`
- `nx generate ngx-deploy-npm:install`
- **Run publish on vite-swc**

**Comment by mogulx-operates** [comment] 2023-02-28 17:11
> > @mogulx-operates, can you please fill in the above list to try to reproduce your error?
> 
> Meh, moving on. Try to publish a package with the latest version of nx and you'll reproduce the error.
> 
> * Node: v16.18.0
> * `npx create-nx-workspace@15.7.2 preset-ts --preset=ts`
> * `npx nx@15.7.2 generate @nrwl/js:library vite-swc --unitTestRunner=vitest --bundler=vite --compiler=swc --directory=web --publishable --importPath=vite-swc`
> * `npm install --save-dev ngx-deploy-npm`
> * `nx generate ngx-deploy-npm:install`
> * **build vite-swc**
> * **Run publish on vite-swc** (assumes there's something to publish)

I lied this works with this configuration.  I'll spin up a repo with this working "workspace" and a workspace that repros.

**Comment by dianjuar** [comment] 2023-03-28 01:37
We are closing the issue.
There needs to be more information to reproduce it.

---

I assume your current Nx version has a bug with the `nrwl/dev-kit` (dependency of ngx-deploy-npm). We recently [closed an issue](https://github.com/bikecoders/ngx-deploy-npm/issues/494) due to the same reason

**Closed by dianjuar** 2023-03-28 01:37 UTC
