### ISSUE TITLE
ngx-deploy-npm:deploy fails with nx 15.4.4

### ISSUE THREAD

**Issue by kurtinatlanta** [bikecoders/ngx-deploy-npm#454] opened 2023-01-04 22:17 UTC
It might fail in other 15.4.x versions as well.

I notice the plugin depends on a specific version of nx. If I remove ngx-deploy-npm/node-modules so that `require("@nrwl/devkit")` pulls the 15.4.4 version instead of the 15.2.3 version, the deploy target succeeds.

Here is the error I get (had to retype by hand, hopefully no typos):
```
TypeError: Cannot read properties of undefined (reading 'nodes')
  at splitTarget (/Users/.../node_modules/nx/src/utils/split-target.js:7:51)
  at parseTargetString (/Users/.../node_modules/ngx-deploy-npm/node_modules/@nrwl/devkit/src/executors/parse-target-string.js:17:77)
  at /Users/.../node_modules/ngx-deploy-npm/src/executors/deploy/actions.js:10:66
  at Generator.next (<anonymous>)
  at /Users/.../node_modules/tslib/tslib.js:118:75
  at new Promise (<anonymous>)
  at Object.__awaiter (/Users/.../node_modules/tslib/tslib.js:114:16)
  at deploy (/Users/.../node_modules/ngx-deploy-npm/src/executors/deploy/actions.js:8:20)
  at /Users/.../node_modules/ngx-deploy-npm/src/executors/deploy/executor.js:14:14
  at Generator.next (<anonymous>)
Error when trying to publish the library
```
It looks like your "local" (15.2.3) version of nx is getting the "global" (15.4.4) version of nx when `parseTargetString` is run, causing the error since they are different versions.

I notice you have a PR ready to update this repo to 15.4.4. Could you merge and rebuild to clear this up?

**Comment by samuelfernandez** [comment] 2023-01-05 10:49
Being affected here as well. Next nrwl pipeline is failing https://github.com/bikecoders/ngx-deploy-npm/actions/workflows/next-test.yml

**Comment by jbadeau** [comment] 2023-01-09 10:24
Also affected, really would appreciate a patch

**Comment by ild0tt0re** [comment] 2023-01-09 12:14
Same error.
I'm on Nx `15.4.5`

**Comment by jbadeau** [comment] 2023-01-09 16:12
As a work around you can use

```json
  "resolutions": {
    "@nrwl/devkit": "^15.4.5"
  }
```

**Comment by dianjuar** [comment] 2023-01-10 16:08
Hello everyone.

Updating to V15.4.X is on the roadmap.
Currently, there are two problems with it.

## Plugin not working for Angular Workspaces
https://github.com/bikecoders/ngx-deploy-npm/actions/runs/3859037630/jobs/6578212774

We offer support for Angular workspaces, and with that version, our tests indicate that our Angular users would remain without support if we update to that version. The problem [seems to be on the Nx side](https://github.com/nrwl/nx/issues/14013).

## Integration tests failing for React and React Native
https://github.com/bikecoders/ngx-deploy-npm/actions/runs/3859037630/jobs/6578189754

The fix looks easy. It takes less time to solve.

---

For now, judging by the comment's reactions, it seems @jbadeau 's [workaround](
https://github.com/bikecoders/ngx-deploy-npm/issues/454#issuecomment-1375883554) is working

We're going to think about other solutions to this problem. In the past, we have faced these kinds of situations, and [potential solutions](https://github.com/bikecoders/ngx-deploy-npm/pull/297#issuecomment-1155309656) risen

**Comment by kurtinatlanta** [comment] 2023-01-10 22:30
`resolutions` works for Yarn users. I use npm (so gauche, i know) and I think `overrides` will work. I'm trying that out tonight/tomorrow to see if that will get me through.

**Comment by dianjuar** [comment] 2023-01-16 15:57
On v15.5.1, all the problems seem to be fixed
https://github.com/bikecoders/ngx-deploy-npm/pull/448

In the next hours, we'll publish it

**Comment by dianjuar** [comment] 2023-01-17 04:18
False alarm.

The [PR](https://github.com/bikecoders/ngx-deploy-npm/pull/448) made by Renovate was confusing. It said it was updating all Nx to V15.5.1, but it wasn't.

The problem is still present.

**Comment by dianjuar** [comment] 2023-01-17 05:19
On PR #460 we are making the fix for this issue.

Everything on Nx is working fine, but the plugin is not working in Angular Workspace for another reason. https://github.com/nrwl/nx/issues/14013 is no longer a problem, but a function provided by Nx [is not working as expected](https://github.com/nrwl/nx/issues/14413).

I would recommend to keep with the workaround provided by @jbadeau

**Comment by samuelfernandez** [comment] 2023-01-17 12:07
Would it be possible to release a new version with the fix for nx workspaces as we await the one for angular?

**Comment by dianjuar** [comment] 2023-01-17 15:04
@samuelfernandez RIght now, it's not.
We would need to modify the Release CI process to skip angular tests. Right now, they are required

**Comment by dianjuar** [comment] 2023-01-24 20:37
Since the fix isn't on the horizon and the wider affected users by this are the ones using Nx, I will make the necessary modifications to the CI pipeline to make the Angular Test optional and land the solution for Nx,

The Angular users don't need to update, but Nx's ones do. It is the right move.

**Comment by shairez** [comment] 2023-01-24 22:15
thanks @dianjuar !

**Comment by dianjuar** [comment] 2023-01-25 17:40
In the meantime, you can comment on the [Nx Issue](https://github.com/nrwl/nx/issues/14413) describing how that issue affects you. That might prioritise the ticket

**Comment by dianjuar** [comment] 2023-01-26 15:08
Hello folks.
On ngx-deploy-npm V4.3.11, you will get the fix for this issue.
Thank you so much for your patience on this. 
Please let me know if everything is working as expected.

**Comment by dianjuar** [comment] 2023-01-26 15:12
One way to contribute to this project (and I would appreciate it) is by going to https://github.com/nrwl/nx/issues/14413 and commenting or reacting to the issue affecting other users of this project.

**Comment by samuelfernandez** [comment] 2023-01-26 18:20
Thanks so much @dianjuar

**Comment by jbadeau** [comment] 2023-01-26 18:20
Thanx too

**Comment by dianjuar** [comment] 2023-02-04 01:45
We will never again have these kinds of problems with [ngx-deploy-npm@5.0.0](https://www.npmjs.com/package/ngx-deploy-npm/v/5.0.0).

Thank you, @samuelfernandez for the work done on #473

**Closed by dianjuar** 2023-02-04 01:45 UTC
